/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
    public static void main(String[] args) {
        Squirrel cheeks = new Squirrel("Cheeks");
        Node nodeOne = new Node(cheeks);
        Squirrel squeaks = new Squirrel("Squeaks");
        Node nodeTwo = new Node(squeaks);
        Squirrel fluffybutt = new Squirrel("Mr. Fluffy Butt");
        Node nodeThree = new Node(fluffybutt);
        nodeOne.set_left(nodeTwo);
        nodeOne.set_right(nodeThree);
        Node retrievedLeft = nodeOne.left();
        Node retrievedRight = nodeOne.right();
        System.out.println("left child: " + retrievedLeft.getData().getName());
        System.out.println("right child: " + retrievedRight.getData().getName());

    }
}